name: Containerfile build 

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: self-hosted 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Docker Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin REGISTRY_URL
      env:
        REGISTRY_URL: quay.io/ebelarte

    - name: Build and push Docker image
      run: |
        docker build -t $REGISTRY_URL/rhel-bootc:bootc-checks .
        docker push $REGISTRY_URL/rhel-bootc:bootc-checks
