name: Containerfile build 

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: self-hosted 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | podman login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin $REGISTRY_URL
      env:
        REGISTRY_URL: quay.io/ebelarte

    - name: Build and push container bootc image
      run: |
        podman build -t $REGISTRY_URL/rhel-bootc:bootc-checks -f Containerfile 
        podman push $REGISTRY_URL/rhel-bootc:bootc-checks
      env:
        REGISTRY_URL: quay.io/ebelarte

